package com.example.gymmanager.model

// We set default values so Firebase can easily convert this class to a database document and back.
data class Member(
    val id: String = "",              // Unique ID generated by Firestore
    val name: String = "",
    val phoneNumber: String = "",
    val joinDate: Long = 0L,          // Saving dates as Long (timestamps) is much easier for calculations later
    val expiryDate: Long = 0L,
    val feePaid: Double = 0.0,
    val isActive: Boolean = true      // Soft delete: instead of deleting, we just mark them inactive
)