package com.example.gymmanager.model

import com.google.firebase.firestore.PropertyName


data class Member(
    val id: String = "",              // Unique ID generated by Firestore
    val name: String = "",
    val phoneNumber: String = "",
    val joinDate: Long = 0L,          // Saving dates as Long (timestamps) is much easier for calculations later
    val expiryDate: Long = 0L,
    val feePaid: Double = 0.0,

    @get:PropertyName("isActive")
    @set:PropertyName("isActive")
    var isActive: Boolean = true ,     // Soft delete: instead of deleting, we just mark them inactive
    val planMonths: Int = 1,
    val lastPaymentDate: Long = System.currentTimeMillis(),
    val lastPaymentAmount: Double = 0.0
)