package com.example.gymmanager.model

import com.google.firebase.firestore.PropertyName



data class PaymentRecord(
    val amount: Double = 0.0,
    val date: Long = System.currentTimeMillis(),
    val description: String = "" // e.g., "Registration", "Renewal", "Cleared Dues"
)

data class Member(
    val id: String = "",              // Unique ID generated by Firestore
    val name: String = "",
    val phoneNumber: String = "",
    val dob: String = "",
    val address: String = "",
    val joinDate: Long = 0L,          // Saving dates as Long (timestamps) is much easier for calculations later
    val expiryDate: Long = 0L,

    val totalPlanFee: Double = 0.0,    // How much the plan actually costs
    val feePaid: Double = 0.0,         // How much they have paid so far
    val pendingBalance: Double = 0.0,  // totalPlanFee - feePaid

    @get:PropertyName("isActive")
    @set:PropertyName("isActive")
    var isActive: Boolean = true ,     // Soft delete: instead of deleting, we just mark them inactive
    val planMonths: Int = 1,
    val lastPaymentDate: Long = System.currentTimeMillis(),
    val lastPaymentAmount: Double = 0.0,

    val paymentHistory: List<PaymentRecord> = emptyList()
)